USE IMPORTER;
DROP PROCEDURE IF EXISTS LGRSU_ADD;
DELIMITER //

CREATE PROCEDURE LGRSU_ADD(IN AWTCH INT ,IN AKGRS INT,IN ANGRS VARCHAR(90),IN AKDJM INT,IN ASGRS CHAR(1) )
MODIFIES SQL DATA
BEGIN
DECLARE VKGRS INT;
DECLARE ALREADY_EXISTS INT DEFAULT 0;
DECLARE CONTINUE HANDLER FOR SQLSTATE '23000' SET ALREADY_EXISTS=1;

SELECT KGRS INTO VKGRS FROM LGRSU WHERE KGRS=AKGRS AND NGRS=ANGRS AND KDJM=AKDJM AND SGRS=ASGRS;
IF VKGRS IS NULL THEN
    INSERT INTO LGRSU(KGRS,NGRS,KDJM,SGRS) VALUES(AKGRS,ANGRS,AKDJM,ASGRS);
    IF ALREADY_EXISTS = 0 THEN
        INSERT INTO LHGRS(KGRS,NGRS,KDJM,SGRS,WTCH) VALUES(AKGRS,ANGRS,AKDJM,ASGRS,AWTCH);
    END IF;     
ELSE
    UPDATE LGRSU SET NGRS=ANGRS,KDJM=AKDJM,SGRS=ASGRS WHERE KGRS=AKGRS;
    INSERT INTO LHGRS(KGRS,NGRS,KDJM,SGRS,WTCH) VALUES(AKGRS,ANGRS,AKDJM,ASGRS,AWTCH); 
END IF;


END;
//